name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  compile:
    name: Compile Scada-LTS application
    if: 'false' # Skip this job
    runs-on: ubuntu-latest
    env:
      CATALINA_HOME: /opt/tomcat/apache-tomcat-7.0.108
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Tomcat
        run: sudo mkdir /opt/tomcat; cd /opt/tomcat; sudo wget https://apache.mirrors.tworzy.net/tomcat/tomcat-7/v7.0.108/bin/apache-tomcat-7.0.108.tar.gz; sudo tar xvzf apache-tomcat-7.0.108.tar.gz
      - name: Cache Tomcat
        uses: actions/cache@v2
        env:
          cache-name: cache-tomcat
        with:
            key: ${{ runner.os }}-${{ github.run_id }}
            path: $CATALINA_HOME
      - name: Build WAR file with Ant
        run: ant -noinput -buildfile build.xml build-project
  buildui:
    name: Build Scada-LTS new User Interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.run_id }}
      - name: Install dependencies
        working-directory: ./scadalts-ui
        run: npm install
      - name: Run Frontend UnitTests
        working-directory: ./scadalts-ui
        run: npm run-script test:unit
      - name: Prepare Application Vairables
        working-directory: ./scadalts-ui
        run: npm run-script build-config -- $SCADA_LTS_MILESTONE $GITHUB_ACTION $GITHUB_REF $GITHUB_SHA $GITHUB_BASE_REF $GITHUB_HEAD_REF
      - name: Build Frontend application
        working-directory: ./scadalts-ui
        run: npm run-script build
      - name: Cache Frontend
        uses: actions/cache@v2
        env:
          cache-name: cache-frontend
        with:
          key: ${{ runner.os }}-ui-${{ github.run_id }}
          path: ${{github.workspace}}/scadalts-ui/dist
  deploy:
    name: Build and Deploy Scada-LTS application
    needs: [compile, buildui]
    if: 'false' # Skip this job
    runs-on: ubuntu-latest
    env:
      CATALINA_HOME: /opt/tomcat/apache-tomcat-7.0.108
    steps:
      - name: Cache Tomcat
        uses: actions/cache@v2
        env:
          cache-name: cache-tomcat
        with:
          key: ${{ runner.os }}-${{ env.cache-name }}-{{ hashFiles('$CATALINA_HOME') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-{{ hashFiles('$CATALINA_HOME') }}
            ${{ runner.os }}-${{ env.cache-name }}-
          path: $CATALINA_HOME
#      - name: Deploy WAR artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: Scada-LTS.war
#          path: ScadaBR.war


